In [1]:
import numpy as np

### Manually creating arrays

In [2]:
oned_arr = np.array([1,2,3])
twod_arr = np.array([[1,2,3], [4,5,6]])

In [3]:
oned_arr, twod_arr

(array([1, 2, 3]), array([[1, 2, 3],
        [4, 5, 6]]))

len(a) returns the size of first dimension of a

In [4]:
oned_arr.shape, oned_arr.ndim, len(oned_arr)

((3,), 1, 3)

In [5]:
twod_arr.shape, twod_arr.ndim, len(twod_arr)

((2, 3), 2, 2)

In [6]:
oned_arr.dtype

dtype('int32')

### Functions for creating Arrays

In [7]:
# to generate equaly spaced array with elements between(inclusive) 
# starting and ending point, with step

new_arr = np.arange(2, 20, 4)  # start, end, step
new1_arr = np.arange(8)

In [8]:
new_arr, new1_arr

(array([ 2,  6, 10, 14, 18]), array([0, 1, 2, 3, 4, 5, 6, 7]))

In [9]:
new_arr.dtype, new1_arr.dtype

(dtype('int32'), dtype('int32'))

In [10]:
new_arr.astype('float64')

array([ 2.,  6., 10., 14., 18.])

In [11]:
# to generate eqyaly spaced n(num_points) array elements
# between(inclusive) start and end points

new_arr = np.linspace(1,5,3)  # start, end, num_points
new_arr, new_arr.dtype

(array([1., 3., 5.]), dtype('float64'))

In [12]:
# arrays of ones and zeros

ones_arr = np.ones((5,3))
zeros_arr = np.zeros((4,3))
ones_arr, zeros_arr

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [13]:
ones_arr.dtype, zeros_arr.dtype

(dtype('float64'), dtype('float64'))

In [14]:
# array of random numbers between 0 and 1

arr = np.random.rand(5)
arr

array([0.83230299, 0.63755409, 0.86633234, 0.42822831, 0.30745356])

In [15]:
# generate n(num) random integers b/w start(inclusive) and end

arr = np.random.randint(0,11,3) #start, end, num
arr

array([ 6,  6, 10])

In [16]:
# generate n(num) numbers from normal distribution with 
# mean m, standard deviation std

arr = np.random.normal(2.0,1.0, 5) #mean, std, num
arr

array([3.6651872 , 2.48250125, 3.4647904 , 2.63284906, 0.57494358])

### Slicing  of array

In 2D, the first dimension is row, the second is column

In [17]:
arr = np.array([[1,2,3,4,5], [15,16,17,18,19], [6,8,10,12,14]])

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [15, 16, 17, 18, 19],
       [ 6,  8, 10, 12, 14]])

In [19]:
#selecting first row of arr
arr[0]

array([1, 2, 3, 4, 5])

In [20]:
#select the last row of arr
print(arr[-1])

#select the 1st row and 2nd column
print(arr[0:,1])

[ 6  8 10 12 14]
[ 2 16  8]


In [21]:
#select all elements of arr
arr[::, ::]  # start:end:step 

array([[ 1,  2,  3,  4,  5],
       [15, 16, 17, 18, 19],
       [ 6,  8, 10, 12, 14]])

In [22]:
# first row and first column

arr[0], arr[::,0]

(array([1, 2, 3, 4, 5]), array([ 1, 15,  6]))

In [23]:
arr[0:2, ::] # row at index 2 is not included

array([[ 1,  2,  3,  4,  5],
       [15, 16, 17, 18, 19]])

In [24]:
# reversing the array

arr[-1::], arr[::]

(array([[ 6,  8, 10, 12, 14]]), array([[ 1,  2,  3,  4,  5],
        [15, 16, 17, 18, 19],
        [ 6,  8, 10, 12, 14]]))

###  Numerical Operations on Arrays

In [25]:
arr = np.array([[1,2,3,4,5], [15,16,17,18,19], [6,8,10,12,14]])

In [26]:
newArr = arr+1
newArr

array([[ 2,  3,  4,  5,  6],
       [16, 17, 18, 19, 20],
       [ 7,  9, 11, 13, 15]])

In [27]:
newArr-arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
arr.transpose()

array([[ 1, 15,  6],
       [ 2, 16,  8],
       [ 3, 17, 10],
       [ 4, 18, 12],
       [ 5, 19, 14]])

In [29]:
# Elementwise sum
print(newArr + arr) #or
print(np.add(newArr, arr))

[[ 3  5  7  9 11]
 [31 33 35 37 39]
 [13 17 21 25 29]]
[[ 3  5  7  9 11]
 [31 33 35 37 39]
 [13 17 21 25 29]]


In [30]:
# Elementwise multiplication
print(newArr * arr) #or
print(np.multiply(newArr, arr))

[[  2   6  12  20  30]
 [240 272 306 342 380]
 [ 42  72 110 156 210]]
[[  2   6  12  20  30]
 [240 272 306 342 380]
 [ 42  72 110 156 210]]


In [31]:
np.sqrt(newArr)

array([[1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [2.64575131, 3.        , 3.31662479, 3.60555128, 3.87298335]])

###### Dot Product

In [32]:
a = np.array((2,3,4))
b = np.array((5,6,7))

In [33]:
np.dot(a[1], arr)

array([[ 3,  6,  9, 12, 15],
       [45, 48, 51, 54, 57],
       [18, 24, 30, 36, 42]])

In [34]:
np.dot(a, b)

56

###### Comparisons

In [35]:
arr == newArr

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [36]:
(arr == newArr).sum()

0

In [37]:
(arr > newArr).sum() ,  (arr< newArr).sum()

(0, 15)

In [38]:
np.array_equal(arr, newArr)

False

### Array Shape Manipulation

In [39]:
arr = np.array([[1,2,3,4,5], [15,16,17,18,19], [6,8,10,12,14]])

In [40]:
# transpose

print(arr.T)          # or
print(arr.transpose())

[[ 1 15  6]
 [ 2 16  8]
 [ 3 17 10]
 [ 4 18 12]
 [ 5 19 14]]
[[ 1 15  6]
 [ 2 16  8]
 [ 3 17 10]
 [ 4 18 12]
 [ 5 19 14]]


In [41]:
arr.size

15

In [42]:
# Flattening 

arr.ravel()  # or
# arr.reshape(-1)

array([ 1,  2,  3,  4,  5, 15, 16, 17, 18, 19,  6,  8, 10, 12, 14])

In [43]:
# Reshaping
arr.reshape((1,15))

array([[ 1,  2,  3,  4,  5, 15, 16, 17, 18, 19,  6,  8, 10, 12, 14]])

Both resize() and reshape() change the shape of numpy array.
 The difference is that using resize() will affecty the original array while reshape() create a new reshaped instance of the array.

### Sorting

In [44]:
# sorting along an axis

np.sort(arr, axis=0)  #or for inplace sorting
# arr.sort(axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14],
       [15, 16, 17, 18, 19]])

In [45]:
# finding minima and maxima

np.min(arr), np.max(arr)

(1, 19)

In [46]:
# finding the index of maximum and minimum

np.argmax(arr), np.argmin(arr)

(9, 0)